---
title: "Dependent variable"
author: "Natalia Mejia"
date: "23/2/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)

```

```{r}
#Getting the datasets

data2010_raw <- read_dta("peopleu.dta") #Sample size 22.179 observations
data2013_raw <- read_dta("peopleu2013.dta") #Sample size 20.574 observations
data2016_raw <- read_dta("peopleu2016.dta") #Sample size 19.298

#Renaming the variables

data2010 <- data2010_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo)

data2013 <- data2013_raw %>% 
   rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar)

data2016 <- data2016_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar)

#Recoding variable wave

data2010$wave <- 2010 
data2013$wave <- 2013 
data2016$wave <- 2016 

#Recoding variable inedu

data2010$inedu[data2010$inedu == 2] <- 0
data2013$inedu[data2013$inedu == 2] <- 0
data2016$inedu[data2016$inedu == 2] <- 0


#Recoding varible edu_mom and edu_dad

data2010$educ_dad <- factor(data2010$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2013$educ_dad <- factor(data2013$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
data2016$educ_dad <- factor(data2016$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2010$educ_mom <- factor(data2010$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
data2013$educ_mom <- factor(data2013$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2016$educ_mom <- factor(data2016$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
```


```{r}
#Dataset wave 1

#Select the variables of interest 
subset1_w1 <- subset(data2010, select = c("id", "wave", "age","inedu"))
#Sample size 22.179

#Drop all NA´s from ID variable
subset2_w1 <- subset(subset1_w1, !is.na(id))
#Sample size 22.179

#Select only the subjects that are studying at the moment of the survey(baseline)
subset3_w1 <- subset(subset2_w1, inedu == 1)
#Sample size 2.574

wave1 <- subset3_w1 #Sample size wave1 2.547
summary(wave1$age)

```

```{r}
#Dataset wave 2

#Select variables of interest
subset1_w2 <- subset(data2013, select = c("id","wave", "age",
                                          "inedu"))
#Sample size 20.547

#Drop all NA´s from ID variable
subset2_w2 <- subset(subset1_w2, !is.na(id))
#Sample size 17.064

wave2 <- subset2_w2 #Sample size wave2 17.064

table(wave2$inedu)
table(wave2$age)
```

```{r}
#Dataset wave 3

#Select variables of interest
subset1_w3 <- subset(data2016, select = c("id", "wave", "age", "inedu"))
#Sample size 19.298

subset2_w3 <- subset(subset1_w3, !is.na(id))
#Sample size 14.944

wave3 <- subset2_w3 #Sample size wave3 14.944
table(wave3$inedu)
summary(wave3$age)

```


```{r}
#Append the datasets

data2010_2016 <- rbind(wave1, wave2, wave3) #Sample size 34.555

#Drop all NA´s from inedu variable
subset1 <- subset(data2010_2016, !is.na(inedu))
#Sample size 32.800

#Subset the data to ages between 6 and 17(compulsory education in Colombia)
subset2 <- subset(subset1, age >= 6 & age <= 17)
#Sample size 10.313

data01 <- subset2
#Sample size data01 10.313

summary(data2010_2016$inedu)
```

```{r}
#Shape the dataset as panel data for the dependent variable inedu

dependentv <- pdata.frame(data01, index=c("id","wave"), drop.index=TRUE, row.names=TRUE)

```

```{r}
#Frequency tables for the dependent variable inedu

freq_depv <- dependentv %>% 
  count(inedu) %>%
  mutate("Percentage" = n / sum(n) *100) %>%
  kable(caption = "Percentage of observations by case in inedu variable", 
        align = "c") %>% kable_styling(full_width = F)

freq_depv

```


```{r}

dependentv_table <- table(dependentv) %>%
  kable(caption = "Distribution of variable inedu by age",
        col.names = c("Inedu = 0", "Inedu = 1"),
        align = "c") %>% 
   kable_minimal()

dependentv_table

```

```{r}
#Running pglm model with inedu and age 

model <- pglm(inedu ~ age, model = "pooling", family = binomial("probit"), data = dependentv)

summary(model)

```
```{r}
#Independent variable: parents education

#Subsetting the data2010 to get variables of interest 

parent_educ <- subset(data2010, select = c ("id","educ_dad", "educ_mom")) 
#Sample size 22.179

#Removing NAs from the parent education variables

subset1_parent <- subset(parent_educ, !is.na(educ_dad))
#Sample size 15.510

subset2_parent <- subset(subset1_parent, !is.na(educ_mom))
#10.648

subset3_parent <- subset(subset2_parent, educ_dad != "No info")
#Sample size 10.512

subset4_parent <- subset(subset3_parent, educ_mom != "No info")
#Sample size 10.500

parent_edu2010 <- subset4_parent #10.500

summary(parent_educ$educ_mom)
summary(parent_educ$educ_dad)

```

```{r}

freq_dad <- parent_edu2010 %>% 
  count(educ_dad) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Percentage of observations by case in educ_dad variable", 
        align = "c") %>% kable_styling(full_width = F)

freq_dad

```

```{r}
freq_mom <- parent_edu2010 %>% 
  count(educ_mom) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Percentage of observations by case in educ_mom variable", 
        align = "c") %>% kable_styling(full_width = F)

freq_mom

```

```{r}
#Merging the parentedu with the dependent variable inedu

parent_inedu_raw <- merge(data01, parent_edu2010, by= "id", all.x = TRUE)
#Sample size 10.313

subset_inedu <- subset(parent_inedu_raw, !is.na(educ_mom))
#Sample 511

parent_inedu <- subset_inedu
#Sample 511

```


```{r}
#Distribution of variable educ_dad analytical sample depv inedu

freq_dad2 <- parent_inedu %>% 
  count(educ_dad) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Percentage of observations by case in educ_dad variable", 
        align = "c") %>% kable_styling(full_width = F)

freq_dad2
```

```{r}
#Distribution of variable mom_educ analytical sample depv inedu

freq_mom2 <- parent_inedu %>% 
  count(educ_mom) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Percentage of observations by case in educ_mom variable", 
        align = "c") %>% kable_styling(full_width = F)

freq_mom2

```

```{r}
#Independent variable: household (income)

#Subsetting the data2010 to get variables of interest ocupation and income

income2010_raw <- subset(data2010, select = c ("id","orden","ocupacion", "vr_salario"))
#Sample 22.178

#Subsetting the data to the members 1 and 2 of the household (leader and partner)
subset_income1 <- subset(income2010_raw, orden == 1 & 2)
#Sample 5.275

#Eliminating the NA´s in de income variable
subset_income2 <- subset(subset_income1, !is.na(vr_salario))
#Sample 2.210

income2010 <- subset_income2

summary(income2010_raw$orden)

#Sample 3.160

summary(income2010$vr_salario)
summary(income2010$ocupacion)

parent_income1 <- merge(wave1, income2010, by= "id", all.x = TRUE)

subset_parent <- subset(parent_income1, !is.na(vr_salario))

```

```{r}
#Merging the household variable with the dependent variable inedu

parent_income1 <- merge(wave1, income2010, by= "id", all.x = TRUE)

subset_parent <- subset(parent_income1, !is.na(vr_salario))

```


 









