---
title: "Thesis data"
author: "Natalia Mejia"
date: "16/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Thesis data

```{r}
library(haven)
library(dplyr)

#Getting the data for survey people urban in 2010

data2010 <- read_dta("peopleu.dta")

```


```{r}
#Subsetting the dataset to the variables of interest for dropout (dependent variable)

dropout <- subset(data2010, select = c("llave_ID_lb", "edad", "sexo", "estudia", "grado_educ_cursa"))

#Limit the sample to kids from 6 to 14 years old

subset1 <- subset(dropout, edad >= 6 & edad <= 14)

#Limit the sample to kids that are enroll at the moment of the survey --> risk population

subset2 <- subset(subset1, estudia == 1)


dropout_clean <- subset2

#Initial sample of 1.732 observations and 9 variables. Removing the NAs from the variables would reduce the sample too much (check this with Michaela)

#Is it ok to reduce the sample to kids from the beginning for the dropout variable?


```

```{r}
#Subsetting the dataset to the variables relevant for the parent education variable

parent_educ <- subset(data2010, select = c ("llave_ID_lb","educ_padre","educ_madre")) 


#Removing NAs from the variables

subset1_parent <- subset(parent_educ, !is.na(educ_padre))
subset2_parent <- subset(subset1_parent, !is.na(educ_madre))


parent_edu_clean <- subset2_parent

#Initial sample of 10.648
```


```{r}
#Subsetting the dataset to the variables relevant for the household income variable

household <- subset(data2010, select = c("llave_ID_lb", "orden","vr_ganancia"))

#Removing NAs from relevant variables

subset1_h <- subset(household, !is.na(vr_ganancia))

household_clean <- subset1_h

#Initial sample of 2.677 and 3 variables 
```


```{r}
#Subsetting the dataset to the variables relevant for the family structure variable

family <- subset(data2010, select = c("llave_ID_lb", "padre_vive", "madre_vive", "vive_conyuge", "otras_unionesm"))

#Removing NAs from the relevant variables

subset1_f <- subset(family, !is.na(vive_conyuge))
subset2_f <- subset(subset1_f, !is.na(padre_vive))
subset3_f <- subset(subset2_f, !is.na(madre_vive))

family_clean <- subset3_f

#Initial sample of 7.110

```


```{r}
#Merging the datasets

dropout_parent <- left_join(dropout_clean, parent_edu_clean, by = "llave_ID_lb")

drop_household <- left_join(dropout_parent, household_clean, by ="llave_ID_lb")

drop_family <- left_join(drop_household, family_clean, by = "llave_ID_lb")


final_data2010 <- drop_family
```


```{r}
#Getting the data for survey people urban in 2013

data2013 <- read_dta("peopleu2013.dta")

```

```{r}
#Subsetting the dataset to the variables of interest for dropout (dependent variable)

dropout2013 <- subset(data2013, select = c("llave_ID_lb","llaveper", "edad","estudia", "estudiaba_2010", "grado_educ_2010", "grado_educ_cursa", "dejo_estudiar", "tipo_estab"))


#Removing NA´s from the dataset

subset1_drop2013 <- subset(dropout2013, !is.na(dejo_estudiar))


dropout2013_clean <- subset1_drop2013


#Initial sample of 3.669

```

```{r}

#Subsetting the dataset to the variables relevant for the parent education variable 2013

parent_educ2013 <- subset(data2013, select = c ("llave_ID_lb", "educ_padre","educ_madre")) 


#Removing NAs from the variables

subset1_parent2013 <- subset(parent_educ2013, !is.na(educ_padre))
subset2_parent2013 <- subset(subset1_parent2013, !is.na(educ_madre))

parent_edu_clean2013 <- subset2_parent2013

#Sample without NA´s from educ_padre of 2.182 and without NA´s from educ_padre and educ_madre the is sample is of 272 observations.

```


```{r}
#Subsetting the dataset to the variables relevant for the household income variable 2013

household2013 <- subset(data2013, select = c("llave_ID_lb", "vr_ganancia"))

#Removing NAs 

subset1_h2013 <- subset(household2013, !is.na(vr_ganancia))


household_clean2013 <- subset1_h2013

#Initial sample of 2.530

```

```{r}
#Subsetting the dataset to the variables relevant for the family structure variable 2013

family2013 <- subset(data2013, select = c("llave_ID_lb", "padre_vive", "madre_vive", "vive_conyuge"))

#Removing NAs from the relevant variables

subset1_f2013 <- subset(family2013, !is.na(vive_conyuge))
subset2_f2013 <- subset(subset1_f2013, !is.na(padre_vive))
subset3_f2013 <- subset(subset2_f2013, !is.na(madre_vive))

family_clean2013 <- subset3_f2013

#Initial sample of 7.514

```

```{r}
#Merging the datasets of 2013

dropout_parent2013 <- left_join(dropout2013_clean, parent_edu_clean2013, by = "llave_ID_lb")

drop_household2013 <- left_join(dropout_parent2013, household_clean2013, by ="llave_ID_lb")

subset_drophouse2013 <- subset(drop_household2013, !is.na(llave_ID_lb))

drop_family2013 <- left_join(subset_drophouse2013, family_clean2013, by = "llave_ID_lb")


final_data2013 <- drop_family2013

```


```{r}
#Join datasets from 2010 and 2013

data2010_data2013 <- left_join(final_data2010, final_data2013, by = "llave_ID_lb")

```

```{r}
#Getting the data for survey people urban in 2016

data2016 <- read_dta("peopleu2016.dta")


```

```{r}
#Subsetting the dataset to the variables of interest for dropout (dependent variable)

dropout2016 <- subset(data2016, select = c("llave_ID_lb","llaveper_n16", "edad","estudia", "grado_educ_cursa","dejo_estudiar", "tipo_estab"))


#Elminate NA´s 

subset1_drop2016 <- subset(dropout2016, !is.na(dejo_estudiar))


dropout_clean2016 <- subset1_drop2016

#Initial sample of 3.397 observations

```

```{r}
#Subsetting the dataset to the variables relevant for the parent education variable 2016

parent_educ2016 <- subset(data2016, select = c ("llave_ID_lb", "educ_padre","educ_madre")) 

#Removing NAs from the variables

subset1_parent2016 <- subset(parent_educ2016, !is.na(educ_padre))
subset2_parent2016 <- subset(subset1_parent2016, !is.na(educ_madre))

parent_edu_clean2016 <- subset2_parent2016

#Sample without NA´s from educ_padre of 1.466 and without NA´s from educ_padre and educ_madre the is sample is of 183 observations.

```

```{r}
#Subsetting the dataset to the variables relevant for the household income variable 2016

household2016 <- subset(data2016, select = c("llave_ID_lb", "vr_ganancia"))

#Removing NAs 

subset1_h2016 <- subset(household2016, !is.na(vr_ganancia))


household_clean2016 <- subset1_h2016

#Initial sample of 2.455

```

```{r}
#Subsetting the dataset to the variables relevant for the family structure variable 2016

family2016 <- subset(data2016, select = c("llave_ID_lb", "padre_vive", "madre_vive", "vive_conyuge"))

#Removing NAs from the relevant variables

subset1_f2016 <- subset(family2016, !is.na(vive_conyuge))
subset2_f2016 <- subset(subset1_f2016, !is.na(padre_vive))
subset3_f2016 <- subset(subset2_f2016, !is.na(madre_vive))

family_clean2016 <- subset3_f2013

#Initial sample of 7.514

```

```{r}
#Merging the datasets of 2016

dropout_parent2016 <- left_join(dropout_clean2016, parent_edu_clean2016, by = "llave_ID_lb")

drop_household2016 <- left_join(dropout_parent2016, household_clean2016, by ="llave_ID_lb")

drop_family2016 <- left_join(drop_household2016, family_clean2016, by = "llave_ID_lb")


final_data2016 <- drop_family2016
```

```{r}
#Join datasets from 2013 and 2016

data2013_data2016 <- left_join(data2010_data2013, final_data2013, by = "llave_ID_lb")


```

