---
title: "Experiment"
author: "Natalia Mejia"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
getwd()

#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)
library(summarytools)
library(gmodels)

```




## Experiment with other variables

```{r}
#Getting the datasets

data2010_raw <- read_dta("peopleu.dta") #Sample size 22.179 observations
data2013_raw <- read_dta("peopleu2013.dta") #Sample size 20.574 observations
data2016_raw <- read_dta("peopleu2016.dta") #Sample size 19.298

#Renaming the variables

data2010 <- data2010_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab) 

data2013 <- data2013_raw %>% 
   rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

data2016 <- data2016_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

#Recoding variable wave

data2010$wave <- 2010 
data2013$wave <- 2013 
data2016$wave <- 2016 

#Recoding variable inedu

data2010$inedu[data2010$inedu == 2] <- 0
data2013$inedu[data2013$inedu == 2] <- 0
data2016$inedu[data2016$inedu == 2] <- 0


#Recoding varible edu_mom and edu_dad

data2010$educ_dad <- factor(data2010$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2013$educ_dad <- factor(data2013$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
data2016$educ_dad <- factor(data2016$educ_dad,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2010$educ_mom <- factor(data2010$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
data2013$educ_mom <- factor(data2013$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))

data2016$educ_mom <- factor(data2016$educ_mom,
                            levels = c(1,2,3,4,5,6,7,8,9,98,99),
                            labels = c("Some years of primary school", 
                                       "All primary school",
                                       "Some years of secundary school",
                                       "All secondary school",
                                       "One or more years of technical educ",
                                       "University without title",
                                       "Univeristy with title",
                                       "Posgrad",
                                       "None",
                                       "Does not know",
                                       "No info"))
#Recoding drop_edu

data2013$drop_edu[data2013$drop_edu == 2] <- 0
data2016$drop_edu[data2016$drop_edu == 2] <- 0

```


```{r}
#Drop_edu variable

#Dataset wave 2

#Select variables of interest
subset1_w2.2 <- subset(data2013, select = c("id","wave", "age", 
                                            "drop_edu", 
                                            "gender",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "income",
                                     "ocupation",
                                     "type_school",
                                     "consecutivo"))
#Sample size 17.064

#Drop all NA´s from ID variable 
subset2_w2.2 <- subset(subset1_w2.2, !is.na(id))
#Sample size 17.064

wave2.2 <- subset2_w2.2 #Sample size wave2 17.064

table(wave2.2$drop_edu) #13.732 NA´s from dejo_estudiar

```

```{r}
#Dataset wave 3

#Select variables of interest
subset1_w3.3 <- subset(data2016, select = c("id", 
                                            "wave", 
                                            "age", 
                                            "drop_edu",
                                            "gender",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "income",
                                     "ocupation",
                                     "type_school",
                                     "consecutivo"))
#Sample size 19.298

subset2_w3.3 <- subset(subset1_w3.3, !is.na(id))
#Sample size 14.944

wave3.3 <- subset2_w3.3 #Sample size wave3 14.944

table(wave3.3$drop_edu) #11.547 NA´s from dejo_estudiar
```


```{r}
#Append the datasets

data2010_2016.1 <- rbind(wave2.2, wave3.3) #Sample size 32,008

#Drop all NA´s from dejo_estudiar
subset1.1 <- subset(data2010_2016.1, !is.na(drop_edu))
#Sample size 6,729

#Subset the data to ages between 5 and 16(compulsory education in Colombia)
subset2.2 <- subset(subset1.1, age >= 5 & age <= 16)
#Sample size 6,628

subset3.3 <- subset(subset2.2, !is.na(educ_dad))
data01.1 <- subset3.3
#Sample size data01.1 6.264

```

```{r}
#Table count and variation dropout

freq_drop_edu <- data01.1 %>% 
  count(drop_edu) %>%
  mutate("Percentage" = n / sum(n) *100) %>%
  kable(caption = "Descriptive statistics of dropouts (drop_edu)", 
        align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover"))

freq_drop_edu
```

```{r}
#Table educ_dad (count and variation)

freq_dad1 <- data01.1 %>% 
  count(educ_dad) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father´s level of education variable(educ_dad)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_dad1

```
```{r}
#Table educ mom (count and variation)

freq_mom1 <- data01.1 %>% 
  count(educ_mom) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(2, round, 2) %>%
  kable(caption = "Descriptive statistics of mother´s level of education (educ_mom)", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))



```


```{r}
#Cross tables drop_edu & educ_mom and educ_dad


dropedu_educ1 <- prop.table(table(data01.1$educ_mom, data01.1$drop_edu),2)*100


dropedu_educ2 <- prop.table(table(data01.1$educ_dad, data01.1$drop_edu),2)*100


dropedu_educ1 %>%
  kable(caption = "Cross tabulation of level of education of the mother and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}
#Table dad_house (count and variation)

dad_house1 <- data01.1 %>% 
  count(dad_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father living in the househol(dad_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


```

```{r}
#Table mom_house (count and variation)

mom_house1 <- data01.1 %>% 
  count(mom_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of mother living in the househol(mom_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


```
```{r}
#Cross prop tables drop_edu & educ_mom and educ_dad


dropedu_house1 <- prop.table(table(data01.1$dad_house, data01.1$drop_edu),2)*100

  
dropedu_house2 <- prop.table(table(data01.1$mom_house, data01.1$drop_edu),2)*100


dropedu_house1 %>%
  kable(caption = "Cross tabulation father living in the household and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

dropedu_house2 %>%
  kable(caption = "Cross tabulation mother living in the household and school dropouts, column %", 
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
```{r}
#Income

freq_income1 <- data01.1  %>% 
  count(income) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of income", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_income1
```


```{r}
#Table count and variation ocupation

freq_ocu1 <- data01.1 %>% 
  count(ocupation) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Descriptive statistics of ocupation of head of the household or partner", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_ocu1
```

```{r}
dropedu_ocu <- prop.table(table(data01.1$ocupation, data01.1$drop_edu),2)*100

dropedu_ocu %>%
  kable(caption = "Cross tabulation of ocupation of the head of the household or partner and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```
```{r}
#Table count and variation type of school

freq_school1 <- data01.1 %>% 
  count(type_school) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of type of school", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_school1
```

```{r}
#Cross tab type of school and drop_edu

dropedu_school <- prop.table(table(data01.1$type_school, data01.1$drop_edu),2)*100

dropedu_school %>%
  kable(caption = "Cross tabulation of type of school and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}
#Table count and variation age

freq_age1 <- data01.1 %>% 
  count(age) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of type of age of students", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_age1


```

```{r}
#Cross tab type of age and drop_edu

dropedu_age <- prop.table(table(data01.1$age, data01.1$drop_edu),2)*100

dropedu_age %>%
  kable(caption = "Cross tabulation of age and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
```{r}
#Table count and variation gender

freq_gender1 <- data01.1 %>% 
  count(gender) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of gender of students", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_gender1
```
```{r}
#Cross tab gender and inedu

dropedu_gender <- prop.table(table(data01.1$gender, data01.1$drop_edu),2)*100

dropedu_gender %>%
  kable(caption = "Cross tabulation of gender and school dropouts, column %",
        col.names = c("dropout = 0", "dropout = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```


```{r}
#Shape the dataset as panel data for the dependent variable inedu

dependentv.1 <- pdata.frame(data01.1, index=c("id","wave"), drop.index=TRUE, row.names=TRUE)
```



