---
title: "Descriptive stats DHS data"
author: "Natalia Mejia"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)
library(forcats)
library(devtools)
library(questionr)
library(crunch)
library(table1)

```

```{r}

setwd("C:/Users/natim/Desktop/Thesis/Thesis2/Data/DHS")

#Getting final data

load("final_data.RData")

```

```{r}
#Recoding variables

#Mom marital status

final_data$mom_marital <- factor(final_data$mom_marital)

final_data$mom_marital <- fct_collapse(final_data$mom_marital,
                                    "1-Married" = c("1-Married"),
                                    "2-Living with partner" = c("2-Living with partner"),
                                    "3-Single" = c("3-Separated", "4-Divorced", "6-Never in union"),
                                    "4-Other" = c("5-Widowed", "7-Dead", "8-Does not know"))
                                   
levels(final_data$mom_marital)

#Dad marital status

final_data$dad_marital <- factor(final_data$dad_marital)

final_data$dad_marital <- fct_collapse(final_data$dad_marital,
                                    "1-Married" = c("1-Married"),
                                    "2-Living with partner" = c("2-Living with partner"),
                                    "3-Single" = c("3-Separated", "4-Divorced", "6-Never in union"),
                                    "4-Other" = c("5-Widowed", "7-Dead", "8-Don´t know"))


levels(final_data$dad_marital)

#Education head of household

final_data$educ_head <- as.factor(final_data$educ_head)


final_data$educ_head <- fct_collapse(final_data$educ_head,
                                    "0-No education" = c("0-No education", "8-Don´t know"),
                                    "1-Primary" = c("1-Primary"),
                                    "2-Secondary" = c("2-Secondary"),
                                    "3-Higher" = c("3-Higher"))
final_data <- final_data %>%
  filter(!is.na(educ_head))


summary(final_data$educ_head)

```


```{r}
#Reason living school for context

label(final_data$reason_school) <- "Reason leaving school"

reason_school <- subset(final_data, final_data$reason_school != "No info")


table1(~ reason_school, 
       data= reason_school,
       caption = "Table XX. Reasons for dropping out of school",
       footnote = "Source: DHS Colombia 2015, own estimates")

```


```{r}
#Summary statistics 

label(final_data$school_status) <- "School status"
label(final_data$gender) <- "Gender"
label(final_data$age) <- "Age"
label(final_data$region) <- "Region"
label(final_data$resi) <- "Type of residence"
label(final_data$wealth) <- "Wealth status"
label(final_data$mom_marital) <- "Mom marital status"
label(final_data$dad_marital) <- "Dad marital status"
label(final_data$educ_head) <- "Level of education head household"


table1(~school_status + gender + age + region + resi + wealth + mom_marital + dad_marital + educ_head, 
       data= final_data,
       caption = "Table 1. Summary statistics main variables",
       footnote = "Source: DHS Colombia 2015, own estimates")
```

```{r}
#Cross tabulation education head and school status


head_school <- prop.table(table(final_data$educ_head, final_data$school_status),2)*100

head_school %>%
  kable(caption = "Cross tabulation head of household education level and school status of the children, column %",
        col.names = c("Dropout = 0", "Attending school = 1"),
        align = "c") %>%
kable_classic(full_width = F, html_font = "Cambria") 

```

```{r}
#Cross tabulation type of residence and school status 


resi_school <- prop.table(table(final_data$resi, final_data$school_status),2)*100

resi_school %>%
  kable(caption = "Cross tabulation type of residence and school status of the children, column %",
        col.names = c("Dropout = 0", "Attending school = 1"),
        align = "c") %>%
kable_classic(full_width = F, html_font = "Cambria") 
```
```{r}
#Cross tabulation wealth and school status 

wealth_school <- prop.table(table(final_data$wealth, final_data$school_status),2)*100

wealth_school %>%
  kable(caption = "Cross tabulation wealth status and school status of the children, column %",
        col.names = c("Dropout = 0", "Attending school = 1"),
        align = "c") %>%
kable_classic(full_width = F, html_font = "Cambria") 
```

```{r}
#Cross tabulation mom marital status and school status 

mom_school <- prop.table(table(final_data$mom_marital, final_data$school_status),2)*100

mom_school %>%
  kable(caption = "Cross tabulation mom marital status and school status of the children, column %",
        col.names = c("Dropout = 0", "Attending school = 1"),
        align = "c") %>%
kable_classic(full_width = F, html_font = "Cambria") 
```
```{r}
#Cross tabulation dad marital status and school status 

dad_school <- prop.table(table(final_data$dad_marital, final_data$school_status),2)*100

dad_school %>%
  kable(caption = "Cross tabulation dad marital status and school status of the children, column %",
        col.names = c("Dropout = 0", "Attending school = 1"),
        align = "c") %>%
kable_classic(full_width = F, html_font = "Cambria") 
```
```{r}
#Creating table cross tabulations dep and indep variables


head_edu <- data.frame("Variables" =
                            c("0-No education", 
                              "1-Primary", 
                              "2-Secondary",
                              "3-Higher"),
                          "Dropout" = c(16.5, 36.1,32.2,15.2),
                          "Attending school" = c(12.7, 33.3, 34.3, 19.6))

wealth <- data.frame("Variables" = 
                            c("Poorest", 
                              "Poor", 
                              "Middle",
                              "Rich",
                              "Richest"),
                          "Dropout" = c(49.3, 23.1, 15, 8.7, 3.8),
                          "Attending school"=c(37.3, 20.6, 16.9, 14.2, 11.1))


mom <- data.frame("Variables" =
                             c("1-Married",
                               "2-Living with partner",
                               "3-Single",
                               "4-Other"),
                           "Dropout" = c(21.3, 50, 22.3, 6.1),
                           "Attending school" = c(27.1, 43, 25, 5.1))

dad <- data.frame("Variables" =
                             c("1-Married",
                               "2-Living with partner",
                               "3-Single",
                               "4-Other"),
                           "Dropout" = c(20.6, 47.2, 16.5, 15.6),
                           "Attending school" = c(28.1, 43.3, 14.5, 14.1))


DATA <- rbind(head_edu, wealth, mom, dad)

kbl(DATA, 
    booktabs = T,
    caption = "Table 2. Cross tabulations dependent and independent variables, column %",
    footnote = "Source: DHS Colombia 2015, own estimates") %>%
  pack_rows("Level of education head household", 1, 4) %>%
  pack_rows("Wealth status", 5, 9) %>%
  pack_rows("Mom marital status", 10, 13) %>%
  pack_rows("Father marital status", 14, 17) %>%
  kable_classic(full_width = F, html_font = "Cambria") 

```

```{r}
model <- glm(school_status ~ gender + resi + educ_head + wealth, data = final_data, family = "binomial")

summary(model)
```
```{r}
exp(coef(model))
```


