---
title: "DHS data thesis"
author: "Natalia Mejia"
date: "23/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)
library(forcats)
library(devtools)
library(questionr)
library(crunch)
library(table1)
```

```{r}
#Getting datasets

setwd("C:/Users/natim/Desktop/Thesis/Thesis2/Data/DHS")

women <-  read_dta("women.dta")
men <- read_dta("men.dta")
household <- read_dta("household.dta")

```


```{r}
#FEMALE SAMPLE

#Creating variable gender

women$gender <- "1-Female"

#Creating variable id

women$id <- women$caseid

#Creating variable household id

women$household_id <- women$v002

#Creating variable region

women$region <- women$v101

#Creating variable school status

women$school_status <- women$s109

#Creating variable time left school

women$time_school <- women$s110

#Creating variable reason left school

women$reason_school <- women$s111

#Creating variable living with

women$living <- women$s118

#Creating variable age

women$age <- women$v012

#Creating variable educational attainment

women$edu <- women$v149

#Creating the variable type of residence

women$resi <- women$v025

#Creating the variable wealth status

women$wealth <- women$v190a

#Creating variable mom marital status

women$mom_marital <- women$s112

#Cresting variable dad marital status

women$dad_marital <- women$s113


#Creating the female dataset

female_raw <- subset(women, select = c(id,
                                   household_id,
                                   gender,
                                   age,
                                   region,
                                   resi,
                                   school_status,
                                   time_school,
                                   reason_school,
                                   edu,
                                   wealth,
                                   living,
                                   mom_marital,
                                   dad_marital)) 
#Sample size 38,718

#Subset the sample to respondents between 11 and 16 years old and respondents age 16 that are no attending school but completed secondary

female <- subset(female_raw, age >= 11 & age <= 16 
                  & !(age == 16 & edu == 4 & school_status == 0))

#Sample size 5,457

```


```{r}
#MALE SAMPLE

#Creating variable gender

men$gender <- "0-Male"

#Creating variable id

men$id <- men$mcaseid

#Creating variable household id

men$household_id <- men$mv002

#Creating variable region

men$region <- men$mv024

#Creating variable school status

men$school_status <- men$sm109

#Creating variable time left school

men$time_school <- men$sm110

#Creating variable reason left school

men$reason_school <- men$sm111

#Creating variable living with

men$living <- men$sm118


#Creating variable age

men$age <- men$mv012

#Creating variable educational attaintment

men$edu <- men$mv149

#Creating the variable type of residence

men$resi <- men$mv025

#Creating the variable wealth status

men$wealth <- men$mv190a

#Creating variable mom marital status

men$mom_marital <- men$sm112

#Cresting variable dad marital status

men$dad_marital <- men$sm113

#Creating the male dataset

male_raw <- subset(men, select = c(id,
                                   household_id,
                                   gender,
                                   age,
                                   region,
                                   resi,
                                   school_status,
                                   time_school,
                                   reason_school,
                                   edu,
                                   wealth,
                                   living,
                                   mom_marital,
                                   dad_marital))

#Subset the sample to respondents between 11 and 16 years old and respondents age 16 that are no attending school but completed secondary

male <- subset(male_raw, age >= 11 & age <= 16 
                  & !(age == 16 & edu == 4 & school_status == 0))

summary(male$reason_school)

```

```{r}
#Join female and male datasets

data01_raw <- full_join(male, female)

data01 <- subset(data01_raw, edu != 5)


#Creating dropout variable and recoding the variable

data01$dropouts[data01$school_status==1] <- 0
data01$dropouts[data01$school_status==0] <- 1


save(data01, file = "data01.RData")
load("data01.RData")
?save

#Sample size 10,942

```


```{r}
#Table count and variation school status

freq_school <- data01 %>% 
  count(school_status) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Table 1. Descriptive statistics of school status", 
        align = "c") %>% 
  kable_classic(full_width = F, html_font = "Cambria")

freq_school

```

```{r}
#Crosstab school_status and age

age<- prop.table(table(data01$age, data01$school_status),2)*100


age %>%
  kable(caption = "Table 2. Cross tabulation of age and school status, column %",
        col.names = c("school_status = 0", "school_status = 1"),
        align = "c") %>%
  kable_classic(full_width = F, html_font = "Cambria")

```


```{r}
#Crosstab school_status and region

region <- prop.table(table(data01$region, data01$school_status),2)*100


region %>%
  kable(caption = "Table 3. Cross tabulation of region and school status, column %",
        col.names = c("school_status = 0", "school_status = 1"),
        row.names(data01$region),
        align = "c") %>%
  kable_classic(full_width = F, html_font = "Cambria")


```


```{r}
#Crosstab school_status and type of residence (urban or rural)

resi <- prop.table(table(data01$resi, data01$school_status),2)*100


resi %>%
  kable(caption = "Table 4. Cross tabulation of type of residence and school status, column %",
        col.names = c("school_status = 0", "school_status = 1"),
        align = "c") %>%
  kable_classic(full_width = F, html_font = "Cambria")

```


```{r}
#Converting variable as factors

data01$school_status <- as.factor(data01$school_status)
data01$region <- as.factor(data01$region)
data01$gender <- as.factor(data01$gender)
data01$age <- as.factor(data01$age)
data01$resi <-as.factor(data01$resi)



model <- glm(school_status ~ region + gender + age + resi, data = data01, family = "binomial")

summary(model)

```



```{r}
#Household variables: relationship to head, age of the household member, school attendance status

household1 <- subset(household, select = c(hhid,
                                           hv002,
                                           hv101_01,
                                           hv101_02,
                                           hv101_03,
                                           hv101_04,
                                           hv101_05,
                                           hv101_06,
                                           hv101_07,
                                           hv101_08,
                                           hv101_09,
                                           hv101_10,
                                           hv101_11,
                                           hv101_12,
                                           hv101_13,
                                           hv101_14,
                                           hv101_15,
                                           hv101_16,
                                           hv101_17,
                                           hv101_18,
                                           hv101_19,
                                           hv101_20,
                                           hv101_21,
                                           hv105_01,
                                           hv105_02,
                                           hv105_03,
                                           hv105_04,
                                           hv105_05,
                                           hv105_06,
                                           hv105_07,
                                           hv105_08,
                                           hv105_09,
                                           hv105_10,
                                           hv105_11,
                                           hv105_12,
                                           hv105_13,
                                           hv105_14,
                                           hv105_15,
                                           hv105_16,
                                           hv105_17,
                                           hv105_18,
                                           hv105_19,
                                           hv105_20,
                                           hv105_21,
                                           hv129_01,
                                           hv129_02,
                                           hv129_03,
                                           hv129_04,
                                           hv129_05,
                                           hv129_06,
                                           hv129_07,
                                           hv129_08,
                                           hv129_09,
                                           hv129_10,
                                           hv129_11,
                                           hv129_12,
                                           hv129_13,
                                           hv129_14,
                                           hv129_15,
                                           hv129_16,
                                           hv129_17,
                                           hv129_18,
                                           hv129_19,
                                           hv129_20,
                                           hv129_21,
                                           hv106_01,
                                           hv106_02,
                                           hv106_03,
                                           hv106_04,
                                           hv106_05,
                                           hv106_06,
                                           hv106_07,
                                           hv106_08,
                                           hv106_09,
                                           hv106_10,
                                           hv106_11,
                                           hv106_12,
                                           hv106_13,
                                           hv106_14,
                                           hv106_15,
                                           hv106_16,
                                           hv106_17,
                                           hv106_18,
                                           hv106_19,
                                           hv106_20,
                                           hv106_21,
                                           hv104_01,
                                           hv104_02,
                                           hv104_03,
                                           hv104_04,
                                           hv104_05,
                                           hv104_06,
                                           hv104_07,
                                           hv104_08,
                                           hv104_09,
                                           hv104_10,
                                           hv104_11,
                                           hv104_12,
                                           hv104_13,
                                           hv104_14,
                                           hv104_15,
                                           hv104_16,
                                           hv104_17,
                                           hv104_18,
                                           hv104_19,
                                           hv104_20,
                                           hv104_21))
#Getting age in long format

data01 <- gather(household1, Age1, age, hv105_01:hv105_21)
subset1 <- subset(data01, select = c(hhid,
                                     age))
#Getting school status in long format
data02 <- gather(household1,School, school_status, hv129_01:hv129_21)
subset2 <- subset(data02, select =c(school_status))

#Getting relationship to head in long format
data03 <- gather(household1, Head, relationship_to_head, hv101_01:hv101_21)
subset3 <- subset(data03, select = c(relationship_to_head))

#Getting level of education in long format
data04 <- gather(household1, Level, level_educ,hv106_01:hv106_21 )
subset4 <- subset(data04, select = c(level_educ))

#Joining long format datasets
data_long <- cbind(subset1, subset3, subset2, subset4)

#Subsetting the long format dataset to respondents age 5 to 24

subset00 <- subset(data_long, age >= 18 & age <= 24)


crosstab <- prop.table(table(subset00$age, subset00$level_educ),2)*100

table(household$hv106_01)

freq_school <- subset00 %>% 
  count(level_educ) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2)

```

