---
title: "First approach DHS data"
author: "Natalia Mejia"
date: "26/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Getting the variables of interest from women´s dataset

women1 <- subset(women, select = c(caseid,
                                   v002,
                                   v012,
                                   v131,
                                   v101,
                                   v106,
                                   v107,
                                   v133,
                                   v149,
                                   v218,
                                   s106a,
                                   s106b,
                                   s109,
                                   s110,
                                   s111,
                                   s112,
                                   s113,
                                   s115,
                                   s116))

subset1 <- subset(women1, v012 >= 12 & v012 <= 16)

summary(women$s109)
table(subset1$v149)
levels(subset1$s109)


freq_students <- subset1 %>% 
  count(s109) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2)


age_school <- prop.table(table(subset1$v012, subset1$s109),2)*100

```

```{r}
subset2 <- subset(subset1, s109 == 0)

#Crosstab ethnicity and school status
ethni_school <- prop.table(table(subset2$v131, subset2$s109),2)*100

```


```{r}
#Crosstab region and school status

region_school <- prop.table(table(subset2$v101, subset2$s109),2)*100

```

```{r}
#Getting the variables of interest from men´s dataset

men1 <- subset(men, select = c(mcaseid,
                               mv012,
                               mv131,
                               mv101,
                               mv106,
                               mv107,
                               mv133,
                               mv149,
                              mv218,
                              sm106a,
                              sm106b,
                              sm109,
                              sm110,
                              sm111,
                              sm112,
                              sm113,
                              sm115,
                              sm116))


man_subset1 <- subset(men1, mv012 >= 12 & mv012 <= 16)


freq_students1 <- man_subset1 %>% 
  count(sm109) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2)


age_school1 <- prop.table(table(man_subset1$mv012, man_subset1$sm109),2)*100

```


```{r}

man_subset2 <- subset(man_subset1, sm109 == 0)

#Crosstab ethnicity and school status
ethni_school1 <- prop.table(table(man_subset2$mv131, man_subset2$sm109),2)*100

```

```{r}
#Crosstab region and school status

region_school1 <- prop.table(table(man_subset2$mv101, man_subset2$sm109),2)*100


```

