---
title: "Dependent variable"
author: "Natalia Mejia"
date: "23/2/2021"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
getwd()

#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)
library(summarytools)
library(gmodels)

```

```{r}
#Getting the datasets

data2010_raw <- read_dta("peopleu.dta") #Sample size 22,179 observations
data2013_raw <- read_dta("peopleu2013.dta") #Sample size 20,574 observations
data2016_raw <- read_dta("peopleu2016.dta") #Sample size 19,298

#Renaming the variables

data2010 <- data2010_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab) 

data2013 <- data2013_raw %>% 
   rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

data2016 <- data2016_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, inedu = estudia, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, drop_edu = dejo_estudiar, income = vr_salario, ocupation = ocupacion, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

#Recoding variable wave

data2010$wave <- 2010 
data2013$wave <- 2013 
data2016$wave <- 2016 

#Recoding variable inedu

data2010$inedu[data2010$inedu == 2] <- 0
data2013$inedu[data2013$inedu == 2] <- 0
data2016$inedu[data2016$inedu == 2] <- 0

#Recoding variable dad_house

data2010$dad_house[data2010$dad_house == 1] <- 1
data2010$dad_house[data2010$dad_house == 2] <- 0
data2010$dad_house[data2010$dad_house == 3] <- 9

data2013$dad_house[data2013$dad_house == 1] <- 1
data2013$dad_house[data2013$dad_house == 2] <- 0
data2013$dad_house[data2013$dad_house == 3] <- 9

data2013$dad_house <- factor(data2013$dad_house,
                            levels = c(1,0,9),
                            labels = c("1", 
                                       "0",
                                       "9"))
                                      
data2016$dad_house[data2016$dad_house == 1] <- 1
data2016$dad_house[data2016$dad_house == 2] <- 0
data2016$dad_house[data2016$dad_house == 3] <- 9

#Recoding variable mom_house

data2010$mom_house[data2010$dad_house == 1] <- 1
data2010$mom_house[data2010$mom_house == 2] <- 0
data2010$mom_house[data2010$mom_house == 3] <- 9

data2013$mom_house[data2013$mom_house == 1] <- 1
data2013$mom_house[data2013$mom_house == 2] <- 0
data2013$mom_house[data2013$mom_house == 3] <- 9

data2016$mom_house[data2016$mom_house == 1] <- 1
data2016$mom_house[data2016$mom_house == 2] <- 0
data2016$mom_house[data2016$mom_house == 3] <- 9

#Recoding variable edu_dad

data2010$educ_dad[data2010$educ_dad == 1] <- 0
data2010$educ_dad[data2010$educ_dad == 2] <- 1
data2010$educ_dad[data2010$educ_dad == 3] <- 2
data2010$educ_dad[data2010$educ_dad == 4] <- 3
data2010$educ_dad[data2010$educ_dad == 5 &
                    data2010$educ_dad == 6] <- 4
data2010$educ_dad[data2010$educ_dad == 7 &
                    data2010$educ_dad == 8] <- 5
data2010$educ_dad[data2010$educ_dad == 9] <- 6

data2010$educ_dad <- factor(data2010$educ_dad,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))
                                      
                                       
data2013$educ_dad[data2013$educ_dad == 1] <- 0
data2013$educ_dad[data2013$educ_dad == 2] <- 1
data2013$educ_dad[data2013$educ_dad == 3] <- 2
data2013$educ_dad[data2013$educ_dad == 4] <- 3
data2013$educ_dad[data2013$educ_dad == 5 &
                    data2013$educ_dad == 6] <- 4
data2013$educ_dad[data2013$educ_dad == 7 &
                    data2013$educ_dad == 8] <- 5
data2013$educ_dad[data2013$educ_dad == 9] <- 6


data2013$educ_dad <- factor(data2013$educ_dad,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))
                                      
data2016$educ_dad[data2016$educ_dad == 1] <- 0
data2016$educ_dad[data2016$educ_dad == 2] <- 1
data2016$educ_dad[data2016$educ_dad == 3] <- 2
data2016$educ_dad[data2016$educ_dad == 4] <- 3
data2016$educ_dad[data2016$educ_dad == 5 &
                    data2016$educ_dad == 6] <- 4
data2016$educ_dad[data2016$educ_dad == 7 &
                    data2016$educ_dad == 8] <- 5
data2016$educ_dad[data2016$educ_dad == 9] <- 6


data2016$educ_dad <- factor(data2016$educ_dad,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))

#Recoding variable edu_mom

data2010$educ_mom[data2010$educ_mom == 1] <- 0
data2010$educ_mom[data2010$educ_mom == 2] <- 1
data2010$educ_mom[data2010$educ_mom == 3] <- 2
data2010$educ_mom[data2010$educ_mom == 4] <- 3
data2010$educ_mom[data2010$educ_mom == 5 &
                    data2010$educ_mom == 6] <- 4
data2010$educ_mom[data2010$educ_mom == 7 &
                    data2010$educ_mom == 8] <- 5
data2010$educ_mom[data2010$educ_mom == 9] <- 6


data2010$educ_mom <- factor(data2010$educ_mom,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))
                                  
data2013$educ_mom[data2013$educ_mom == 1] <- 0
data2013$educ_mom[data2013$educ_mom == 2] <- 1
data2013$educ_mom[data2013$educ_mom == 3] <- 2
data2013$educ_mom[data2013$educ_mom == 4] <- 3
data2013$educ_mom[data2013$educ_mom == 5 &
                    data2013$educ_mom == 6] <- 4
data2013$educ_mom[data2013$educ_mom == 7 &
                    data2013$educ_mom == 8] <- 5
data2013$educ_mom[data2013$educ_mom == 9] <- 6


data2013$educ_mom <- factor(data2013$educ_mom,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))
                                      
data2016$educ_mom[data2016$educ_mom == 1] <- 0
data2010$educ_mom[data2016$educ_mom == 2] <- 1
data2016$educ_mom[data2016$educ_mom == 3] <- 2
data2016$educ_mom[data2016$educ_mom == 4] <- 3
data2016$educ_mom[data2016$educ_mom == 5 &
                    data2016$educ_mom == 6] <- 4
data2016$educ_mom[data2016$educ_mom == 7 &
                    data2016$educ_mom == 8] <- 5
data2016$educ_mom[data2016$educ_mom == 9] <- 6

data2016$educ_mom <- factor(data2016$educ_mom,
                            levels = c(0,1,2,3,4,5,6),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None"))

#Recoding variable income

data2010$income[data2010$income < 877803] <- 1
data2010$income[data2010$income >= 877803] <- 2
data2010$income[data2010$income < 877803] <- 2
data2010$income[data2010$income >= 1755606] <- 3
data2010$income[data2010$income < 2633409]  <- 3            
data2010$income[data2010$income > 2633409]  <- 4                
     
data2010$income<- factor(data2010$income,
                            levels = c(1,2,3,4),
                            labels = c("Less than 1 minimum wage", 
                                       "From 1 to less than 2 minimum wages",
                                       "From 2 to less than 3 minimum wages",
                                     "More than 3 minimum wages"))

data2013$income[data2013$income < 877803] <- 1
data2013$income[data2013$income >= 877803] <- 2
data2013$income[data2013$income < 877803] <- 2
data2013$income[data2013$income >= 1755606] <- 3
data2013$income[data2013$income < 2633409]  <- 3            
data2013$income[data2013$income > 2633409]  <- 4                
     
data2013$income<- factor(data2013$income,
                            levels = c(1,2,3,4),
                            labels = c("Less than 1 minimum wage", 
                                       "From 1 to less than 2 minimum wages",
                                       "From 2 to less than 3 minimum wages",
                                     "More than 3 minimum wages"))

data2016$income[data2016$income < 877803] <- 1
data2016$income[data2016$income >= 877803] <- 2
data2016$income[data2016$income < 1755606] <- 2
data2016$income[data2016$income >= 1755606] <- 3
data2016$income[data2016$income < 2633409]  <- 3            
data2016$income[data2016$income > 2633409]  <- 4                
     
data2016$income<- factor(data2016$income,
                            levels = c(1,2,3,4),
                            labels = c("Less than 1 minimum wage", 
                                       "From 1 to less than 2 minimum wages",
                                       "From 2 to less than 3 minimum wages",
                                     "More than 3 minimum wages"))

#Recoding variable ocupation

data2010$ocupation <- factor(data2010$ocupation,
                            levels = c(1,2,3,4,5,6,7,8,9,10,11),
                            labels = c("Salaried employee of a private company with indefinite-term contract",
                                       "Salaried employee of a private company with fixed-term contract",
                                       "Government employee with indefinite-term contract",
                                       "Government employee with fixed-term contract",
                                       "Laborer or day laborer",
                                       "Domestic worker",
                                       "Independent worker",
                                       "Employer",
                                       "Worker on own farm",
                                       "Unpaid family worker without",
                                       "Other"))  

data2013$ocupation <- factor(data2013$ocupation,
                            levels = c(1,2,3,4,5,6,7,8,9,10,11),
                            labels = c("Salaried employee of a private company with indefinite-term contract",
                                       "Salaried employee of a private company with fixed-term contract",
                                       "Government employee with indefinite-term contract",
                                       "Government employee with fixed-term contract",
                                       "Laborer or day laborer",
                                       "Domestic worker",
                                       "Independent worker",
                                       "Employer",
                                       "Worker on own farm",
                                       "Unpaid family worker without",
                                       "Other"))  

data2016$ocupation <- factor(data2016$ocupation,
                            levels = c(1,2,3,4,5,6,7,8,9,10,11),
                            labels = c("Salaried employee of a private company with indefinite-term contract",
                                       "Salaried employee of a private company with fixed-term contract",
                                       "Government employee with indefinite-term contract",
                                       "Government employee with fixed-term contract",
                                       "Laborer or day laborer",
                                       "Domestic worker",
                                       "Independent worker",
                                       "Employer",
                                       "Worker on own farm",
                                       "Unpaid family worker without",
                                       "Other"))  
#Recoding type of school variable

data2010$type_school[data2010$type_school == 2] <- 0
data2013$type_school[data2013$type_school == 2] <- 0
data2016$type_school[data2016$type_school == 2] <- 0

#Converting variables double as factors

data2010$ocupation <-as.factor(data2010$ocupation)
data2013$ocupation <- as.factor(data2013$ocupation)
data2016$ocupation <- as.factor(data2016$ocupation)

data2010$dad_house <- as.factor(data2010$dad_house)
data2013$dad_house <- as.factor(data2013$dad_house)
data2016$dad_house <- as.factor(data2016$dad_house)

data2010$mom_house <- as.factor(data2010$mom_house)
data2013$mom_house <- as.factor(data2013$mom_house)
data2016$mom_house <- as.factor(data2016$mom_house)

```


```{r}
#Dataset wave 1

#Select the variables of interest 
subset1_w1 <- subset(data2010, select = c("id", 
                                          "wave", 
                                          "age",
                                          "inedu",
                                          "gender",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "income",
                                     "ocupation",
                                     "type_school",
                                     "consecutivo"))
                                     
                                    
                                     
#Sample size 22,179

#Drop all NA´s from ID variable
subset2_w1 <- subset(subset1_w1, !is.na(id))
#Sample size 22,179

wave1 <- subset2_w1 #Sample size wave1 22.179

```

```{r}
#Dataset wave 2

#Select variables of interest
subset1_w2 <- subset(data2013, select = c("id","wave",
                                          "age",
                                          "inedu",
                                          "gender",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "income",
                                     "ocupation",
                                     "type_school",
                                     "consecutivo"))
                                     
#Sample size 20,547

#Drop all NA´s from ID variable
subset2_w2 <- subset(subset1_w2, !is.na(id))
#Sample size 17,064

wave2 <- subset2_w2 #Sample size wave2 17,064

```

```{r}
#Dataset wave 3

#Select variables of interest
subset1_w3 <- subset(data2016, select = c("id", 
                                          "wave", 
                                          "age", 
                                          "inedu",
                                          "gender",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "income",
                                     "ocupation",
                                     "type_school",
                                     "consecutivo"))
                                     
                                
#Sample size 19,298

subset2_w3 <- subset(subset1_w3, !is.na(id))
#Sample size 14,944

wave3 <- subset2_w3 #Sample size wave3 14.944

```


```{r}
#Append the datasets

data2010_2016 <- rbind(wave1, wave2, wave3) #Sample size 54,187
summary(data2010_2016$inedu)

#Drop all NA´s from inedu variable
subset1 <- subset(data2010_2016, !is.na(inedu))
#Sample size 41,198

#Subset the data to ages between 5 and 16(compulsory education in Colombia)
subset2 <- subset(subset1, age >= 5 & age <= 16)
#Sample size 10,358
table(subset1$inedu)

subset3 <- subset(subset2, !is.na(educ_dad))
#Sample size 2,784

data01 <- subset3
#Sample size data01 2,784

```


```{r}
#Table for the dependent variable inedu (count and variation)

freq_depv <- data01 %>% 
  count(inedu) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of individuals attending school(inedu)", 
        align = "c") %>%  kable_styling(bootstrap_options = c("striped", "hover"))

freq_depv

```

```{r}
#Table educ_dad (count and variation)

freq_dad <- data01 %>% 
  count(educ_dad) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father´s level of education variable(educ_dad)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_dad

```

```{r}
#Table educ mom (count and variation)

freq_mom <- data01 %>% 
  count(educ_mom) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of mother´s level of education (educ_mom)", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_mom

```

```{r}
#Cross tables inedu & educ_mom and educ_dad


inedu_educ1 <- prop.table(table(data01$educ_mom, data01$inedu),2)*100


inedu_educ2 <- prop.table(table(data01$educ_dad, data01$inedu),2)*100


inedu_educ1 %>%
  kable(caption = "Cross tabulation of level of education of the mother and individuals attending school, column %",
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

inedu_educ2 %>%
  kable(caption = "Cross tabulation of level of education of the father and individuals attending school, column %",
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


```

```{r}
#Table dad_house (count and variation)

dad_house <- data01 %>% 
  count(dad_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father living in the househol(dad_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

dad_house

```

```{r}
#Table mom_house (count and variation)

mom_house <- data01 %>% 
  count(mom_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of mother living in the househol(mom_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

mom_house

```

```{r}
#Cross prop tables inedu & educ_mom and educ_dad


inedu_house1 <- prop.table(table(data01$dad_house, data01$inedu),2)*100

round(inedu_house1)
  
inedu_house2 <- prop.table(table(data01$mom_house, data01$inedu),2)*100


inedu_house1 %>%
  kable(caption = "Cross tabulation father living in the household and individuals attending school, column %", 
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

inedu_house2 %>%
  kable(caption = "Cross tabulation mother living in the household and individuals attending school, column %", 
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}

freq_income <- data01  %>% 
  count(income) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of income", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_income

```


```{r}
#Table count and variation ocupation

freq_ocu <- data01 %>% 
  count(ocupation) %>%
  mutate("%" = n / sum(n) *100) %>%
  kable(caption = "Descriptive statistics of ocupation of head of the household or partner", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_ocu

```

```{r}
inedu_ocu <- prop.table(table(data01$ocupation, data01$inedu),2)*100

inedu_ocu %>%
  kable(caption = "Cross tabulation of ocupation of the head of the household or partner and individuals attending school, column %",
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}
#Table count and variation type of school

freq_school <- data01 %>% 
  count(type_school) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of type of school", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_school

```

```{r}
#Cross tab type of school and inedu

inedu_school <- prop.table(table(data01$type_school, data01$inedu),2)*100

inedu_school %>%
  kable(caption = "Cross tabulation of type of school and individuals attending school, column %",
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
  
```

```{r}
#Table count and variation age

freq_age <- data01 %>% 
  count(age) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of type of age of students", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_age

```

```{r}
#Cross tab type of age and inedu

inedu_age <- prop.table(table(data01$age, data01$inedu),2)*100

inedu_age %>%
  kable(caption = "Cross tabulation of age and individuals attending school, column %",
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


```{r}
#Table count and variation gender

freq_gender <- data01 %>% 
  count(gender) %>%
  mutate("%" = n / sum(n) *100) %>%
   mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of gender of students", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

freq_gender

```

```{r}
#Cross tab gender and inedu

inedu_gender <- prop.table(table(data01$gender, data01$inedu),2)*100

inedu_gender %>%
  kable(caption = "Cross tabulation of gender and individuals attending school, column %",
        col.names = c("inedu = 0", "inedu = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```











```{r}
#Shape the dataset as panel data for the dependent variable inedu

model01 <- pdata.frame(data01, index=c("id","wave"), drop.index=TRUE, row.names=TRUE) 

```

```{r}
#Running pglm model with inedu 

model <- pglm(inedu ~ educ_dad + age + gender, model = "pooling", family = binomial("probit"), data = model01)

summary(model) 

```








