---
title: "New approach depv"
author: "Natalia Mejia"
date: "14/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#Required packages

library(dplyr)
library(haven)
library(xtable)
library(plm)
library(pglm)
library(broom)
library(knitr) 
library(tidyverse)
library(tidyr)
library(haven)
library(stargazer)
library(kableExtra)
library(knitr)
library(expss)
library(forcats)
library(devtools)
```

```{r}
#Getting the datasets

data2010_raw <- read_dta("peopleu.dta") #Sample size 22.179 observations
data2013_raw <- read_dta("peopleu2013.dta") #Sample size 20.574 observations
data2016_raw <- read_dta("peopleu2016.dta") #Sample size 19.298


#Renaming the variables

data2010 <- data2010_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, level_educ = nivel_educ, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

data2013 <- data2013_raw %>% 
   rename(id = llave_ID_lb, wave = ola, age = edad, level_educ = nivel_educ, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)

data2016 <- data2016_raw %>%
  rename(id = llave_ID_lb, wave = ola, age = edad, level_educ = nivel_educ, educ_dad = educ_padre, educ_mom = educ_madre, gender = sexo, dad_house = padre_vive,mom_house = madre_vive, type_school = tipo_estab)


#Recoding variable wave

data2010$wave <- 2010 
data2013$wave <- 2013 
data2016$wave <- 2016 

#Recoding variable level_educ

#In wave 1

data2010$level_educ <- as.factor(data2010$level_educ)

data2010$level_educ <- fct_collapse(data2010$level_educ,
                                    "0" = c("1", "2","3"),
                                    "1" = c("4", "5", "6", "7", "8",
                                       "9", "10", "11", "12"))
#In wave 2
data2013$level_educ <- as.factor(data2013$level_educ)

data2013$level_educ <- fct_collapse(data2013$level_educ,
                                    "0" = c("1", "2","3"),
                                    "1" = c("4", "5", "6", "7", "8",
                                     "9", "10", "11", "12",
                                     drop = c("88"))) 

#In wave 3
data2016$level_educ <- as.factor(data2016$level_educ)

data2016$level_educ <- fct_collapse(data2016$level_educ,
                                    "0" = c("1", "2","3"),
                                    "1" = c("4", "5", "6", "7", "8",
                                       "9", "10", "11", "12"))

#Recoding variable dad_house

data2010$dad_house <- as.factor(data2010$dad_house)
 
data2010$dad_house <- fct_collapse(data2010$dad_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = c("9")) 

data2013$dad_house <- as.factor(data2013$dad_house)

data2013$dad_house <- fct_collapse(data2013$dad_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = c("8")) 

data2016$dad_house <- as.factor(data2016$dad_house)

data2016$dad_house <- fct_collapse(data2016$dad_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = "8") 

#Recoding variable mom_house

data2010$mom_house <- as.factor(data2010$mom_house)
 
data2010$mom_house <- fct_collapse(data2010$mom_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = c("9")) 


data2013$mom_house <- as.factor(data2013$mom_house)

data2013$mom_house <- fct_collapse(data2013$mom_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = c("8")) 

data2016$mom_house <- as.factor(data2016$mom_house)

data2016$mom_house <- fct_collapse(data2016$mom_house,
                                   "1_In household" = c("1"),
                                   "0_Absent" = c("2"),
                                   "3_Dead" = c("3"),
                                   "No info" = "8")

#Recoding variable educ_dad

#Converting educ_dad as a factor variable
data2010$educ_dad <- as.factor(data2010$educ_dad)

#Grouping the levels in new categories
data2010$educ_dad <- fct_collapse(data2010$educ_dad,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4"= c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "7" = c("98", "99"))
                                   
#Renaming the levels
data2010$educ_dad <- factor(data2010$educ_dad,
                            levels = c(0,1,2,3,4,5,6,7),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

#Creating a level for NA´s as "no info"

data2010$educ_dad <- fct_explicit_na(data2010$educ_dad, na_level = "No info")


data2013$educ_dad <- as.factor(data2013$educ_dad)

data2013$educ_dad <- fct_collapse(data2013$educ_dad,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4" = c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "88" = c("88", "10"))
                                  
data2013$educ_dad <- factor(data2013$educ_dad,
                            levels = c(0,1,2,3,4,5,6,88),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

data2013$educ_dad <- fct_explicit_na(data2013$educ_dad, na_level = "No info")


data2016$educ_dad <- as.factor(data2016$educ_dad)

data2016$educ_dad <- fct_collapse(data2016$educ_dad,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4" = c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "99" = c("10"))

data2016$educ_dad <- factor(data2016$educ_dad,
                            levels = c(0,1,2,3,4,5,6, 99),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

data2016$educ_dad <- fct_explicit_na(data2016$educ_dad, na_level = "No info")
       
#Recoding variable edu_mom

data2010$educ_mom <- as.factor(data2010$educ_mom)


data2010$educ_mom <- fct_collapse(data2010$educ_mom,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4"= c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "7" = c("98", "99")) 

data2010$educ_mom <- factor(data2010$educ_mom,
                            levels = c(0,1,2,3,4,5,6,7),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

data2010$educ_mom <- fct_explicit_na(data2010$educ_mom, na_level = "No info")


data2013$educ_mom <- as.factor(data2013$educ_mom)

data2013$educ_mom <- fct_collapse(data2013$educ_mom,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4" = c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "88" = c("88", "10"))
                                  
data2013$educ_mom <- factor(data2013$educ_mom,
                            levels = c(0,1,2,3,4,5,6,88),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

data2013$educ_mom <- fct_explicit_na(data2013$educ_mom, na_level = "No info")


data2016$educ_mom <- as.factor(data2016$educ_mom)

data2016$educ_mom <- fct_collapse(data2016$educ_mom,
                                  "0" = c("1"),
                                  "1" = c("2"),
                                  "2" = c("3"),
                                  "3" = c("4"),
                                  "4" = c("5", "6"),
                                  "5" = c("7", "8"),
                                  "6" = c("9"),
                                  "99" = c("10"))

data2016$educ_mom <- factor(data2016$educ_mom,
                            levels = c(0,1,2,3,4,5,6,99),
                            labels = c("Level 0", 
                                       "Level 1_Primary",
                                       "Level 2_Lower secondary educ",
                                       "Level 3_Upper secondary educ",
                                       "Level 4_Post secondary non-tertiary educ",
                                       "Tertiary edu",
                                       "None",
                                       "Other"))

data2016$educ_mom <- fct_explicit_na(data2016$educ_mom, na_level = "No info")  

#Recoding type of school

#Converting variable as factor

data2010$type_school <- as.factor(data2010$type_school)

data2010$type_school <- factor(data2010$type_school,
                            levels = c(1,2),
                            labels = c("1_Public", 
                                       "2_Private"))
   
data2010$type_school <- fct_explicit_na(data2010$type_school, na_level = "No info")

data2013$type_school <- as.factor(data2013$type_school)

data2013$type_school <- factor(data2013$type_school,
                            levels = c(1,2),
                            labels = c("1_Public", 
                                       "2_Private"))
   
data2013$type_school <- fct_explicit_na(data2013$type_school, na_level = "No info")

data2016$type_school <- as.factor(data2016$type_school)

data2016$type_school <- factor(data2016$type_school,
                            levels = c(1,2),
                            labels = c("1_Public", 
                                       "2_Private"))
   
data2016$type_school <- fct_explicit_na(data2016$type_school, na_level = "No info")

```

```{r}
#Dataset wave 1

#Select the variables of interest 
subset1_w1 <- subset(data2010, select = c("id", 
                                          "wave", 
                                          "age",
                                          "gender",
                                          "level_educ",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "consecutivo"))
#Sample size 22,179

wave1 <- subset1_w1 #Sample size wave1 22.179

```

```{r}
subset1_w2 <- subset(data2013, select = c("id", 
                                          "wave", 
                                          "age",
                                          "gender",
                                          "level_educ",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "consecutivo"))

wave2 <- subset1_w2 #Sample size wave2 20,574

```

```{r}
subset1_w3 <- subset(data2016, select = c("id", 
                                          "wave", 
                                          "age",
                                          "gender",
                                          "level_educ",
                                           "educ_dad",
                                     "educ_mom",
                                     "dad_house",
                                     "mom_house",
                                     "consecutivo"))


wave3 <- subset1_w3 #Sample size wave3 19,298
```

```{r}
data2010_2016 <- rbind(wave1, wave2, wave3) #Sample size 62,051

#Drop all NA´s from level_educ
subset1 <- subset(data2010_2016, !is.na(level_educ))
#Sample size 22,908

#Subset the data to age 18+

subset2 <- subset(subset1, age >= 18)
#Sample size 22,166

data <- subset2

```

```{r}
#Getting the dataset to get the  socioeconomic variable

household2010_raw <- read_dta("hogar2010.dta") #Sample size 5,275 observations

subset_house1 <- subset(household2010_raw, select = c("estrato", "consecutivo")) 

household2010 <- subset_house1 %>%
  rename(strata = estrato)


data01 <- left_join(data, household2010, by = "consecutivo")

data01$strata <- as.factor(data01$strata)

data01$strata <- fct_explicit_na(data01$strata, na_level = "No info")
```


```{r}
freq_depv <- data01 %>% 
  count(level_educ) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of level education", 
        align = "c") %>%  kable_styling(bootstrap_options = c("striped", "hover"))
freq_depv
```

```{r}
DATA <- data.frame("Level of education" = c("No sufficient school degree", "Sufficient school degree"), "N" = c(6767, 15399), "Percentage" = c(30.5, 69.5))

DATA %>% kbl(caption = "Table 1. Descriptive statistics dependen and independent variables") %>%
  kable_classic(full_width = F, html_font = "Cambria")





```





```{r}
#Table educ_dad (count and variation)

freq_dad <- data01 %>% 
  count(educ_dad) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father´s level of education variable(educ_dad)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
freq_dad
```





```{r}
#Table educ mom (count and variation)
freq_mom <- data01 %>% 
  count(educ_mom) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of mother´s level of education (educ_mom)", 
        align = "c") %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))
freq_mom

```

```{r}
#Cross tables level_educ & educ_mom 

level_educ1 <- prop.table(table(data01$educ_mom, data01$level_educ),2)*100


level_educ1 %>%
  kable(caption = "Cross tabulation of level of education of the mother and level of education of individual, column %",
        col.names = c("level_educ = 0", "level_educ = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}
##Cross tables level_educ & educ_dad

level_educ2 <- prop.table(table(data01$educ_dad, data01$level_educ),2)*100

level_educ2 %>%
  kable(caption = "Cross tabulation of level of education of the father and individuals attending school, column %",
        col.names = c("level_educ = 0", "level_educ = 1"),
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r}
#Table dad_house (count and variation)
dad_house <- data01 %>% 
  count(dad_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of father living in the househol(dad_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

dad_house

```
```{r}
#Table mom_house (count and variation)

mom_house <- data01 %>% 
  count(mom_house) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of mother living in the househol(mom_house)", 
        align = "c") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
mom_house
```


```{r}
#Table for socioeconomic stratum (count and variation)
stratum <- data01 %>% 
  count(strata) %>%
  mutate("%" = n / sum(n) *100) %>%
  mutate_at(3, round, 2) %>%
  kable(caption = "Descriptive statistics of socioeconomic stratum", 
        align = "c") %>%  kable_styling(bootstrap_options = c("striped", "hover"))

stratum
```

```{r}
#Getting the datasets

household2010_raw <- read_dta("hogar2010.dta") #Sample size 5,275 observations

subset_house1 <- subset(household2010_raw, select = c("estrato", "consecutivo")) 

household2010 <- subset_house1 %>%
  rename(strata = estrato)


data01 <- left_join(data, household2010, by = "consecutivo")

```

